CREATE TABLE Students
(
    StudentID INT PRIMARY KEY NOT NULL,
    Name NVARCHAR(60) NOT NULL
)

CREATE TABLE Exams
(
    ExamID INT PRIMARY KEY NOT NULL,
    Name NVARCHAR(100) NOT NULL
)

CREATE TABLE StudentsExams
(
    StudentID INT NOT NULL FOREIGN KEY REFERENCES Students(StudentID),
    ExamID INT NOT NULL FOREIGN KEY REFERENCES Exams(ExamID)
)

ALTER TABLE StudentsExams
ADD CONSTRAINT CK_StudentsExams
PRIMARY KEY(StudentID,ExamID)